# Generated by Django 5.1.5 on 2025-03-05 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste_actuel', models.CharField(max_length=255, verbose_name='Poste actuel')),
                ('annees_experience', models.IntegerField(verbose_name="Nombre d'années d'expérience")),
                ('overview', models.TextField(blank=True, null=True, verbose_name='Présentation')),
                ('skills', models.TextField(verbose_name='Compétences')),
                ('languages', models.TextField(verbose_name='Langues')),
                ('certifications', models.TextField(verbose_name='Formations et certifications')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeur', models.CharField(max_length=255, verbose_name='Employeur')),
                ('position', models.CharField(max_length=255, verbose_name='Position')),
                ('missions', models.TextField(verbose_name='Missions')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='cv_generator.cv')),
            ],
        ),
    ]
