# Generated by Django 5.1.5 on 2025-03-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_generator', '0002_alter_experience_missions'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='username',
            field=models.TextField(blank=True, null=True, verbose_name='username'),
        ),
    ]
