# Generated by Django 5.1.5 on 2025-03-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_generator', '0003_cv_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='generated_cvs/'),
        ),
    ]
