# Generated by Django 5.1.5 on 2025-02-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_add_username_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='nul', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
